### ISSUE TITLE
Fix weird 3d texture behavior

### ISSUE THREAD

**Issue by klingerj** [mccannd/Project-Marshmallow#29]

**Comment by mccannd** [comment]
Mostly resolved in commit 6d2f9ba7e945c06bef58aa5e756ce6723dd1f5ef

3D textures were fine. Here was the stupid thing: the paper says it marches A to B steps based on the ray direction relative to the horizon. So I made the march step length (outer - inner) / mix(A, B, ray.y). This is bad and I feel bad. In reality the step size should always be the same; in this case it's some constant times the atmosphere thickness. The 'A to B steps' is just a consequence of the angle, not a targeted number of steps.

This bug was not evident in the old procedural noise version but very evident in the new one. Even after the fix it is still present in some areas, but the main source of the bug is stomped. We can probably eliminate the rest by messing with this new step size.

I will call this closed.
